name: Build WLED Firmware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Firmware for ESP32 and ESP8266
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install PlatformIO
      run: pip install platformio

    - name: Build Firmware for ESP8266 (D1 Mini)
      run: |
        platformio run --environment esp8266_2m  # Builds for ESP8266 (D1 Mini)

    - name: Build Firmware for ESP32
      run: |
        platformio run --environment esp32dev  # Builds for ESP32

    - name: List Build Output
      run: |
        ls -R .pio/build  # This will list all files to check if the firmware.bin exists

    - name: Upload Firmware Artifacts
      uses: actions/upload-artifact@v4  # Updated to v4
      with:
        name: WLED-firmware
        path: |
          .pio/build/esp8266_2m/firmware.bin  # ESP8266 (D1 Mini) firmware
          .pio/build/esp32dev/firmware.bin  # ESP32 firmware
